version: "3.8"
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - bootdocker
  appservice:
    build: ./
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/calculator_problem?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 5055:5055
    networks:
      - bootdocker

networks:
  bootdocker:

